// cross-language validation: the TS solver must reproduce the Python solver
// (offline/velocity/solver.py) on both committed circuit fixtures: Spa (hilly, long) and
// Monza (flat, chicane-heavy): at every fixture mu. The fixtures are generated by
// offline/build_viewer_assets.py from the same line.json geometry the viewer ships.

import { describe, expect, it } from "vitest";
import monzaFixture from "./testdata/velocity_fixture_monza.json";
import spaFixture from "./testdata/velocity_fixture_spa.json";
import type { GT3Vehicle } from "./vehicle";
import { CAP_ITERS, LOAD_TRANSFER_ITERS } from "./vehicle";
import { PHASE_ACCEL, PHASE_BRAKE, VelocitySolver } from "./velocity";

// mirrors offline/velocity/vehicle.py's DEFAULT_GT3; the fixture cases only vary mu
const BASE_VEHICLE: Omit<GT3Vehicle, "mu"> = {
  mass_kg: 1300.0,
  downforce_area_m2: 2.8,
  drag_area_m2: 1.35,
  power_w: 410_000.0,
  air_density_kgpm3: 1.225,
  g_mps2: 9.81,
  v_floor_mps: 2.0,
  wheelbase_m: 2.65,
  cg_height_m: 0.3,
  weight_dist_front: 0.44,
  brake_bias_front: 0.62,
  tyre_load_sensitivity: 0.1,
  aero_balance_front: 0.45,
  fz_floor_frac: 0.02,
  drive_axle: "rear",
};

// these bounds are the fixture's own quantisation floor with an order of magnitude of headroom
// for last-ulp differences between Math.pow and numpy, not a judgement about how close is close
// enough. the generator solves the identical rounded arrays the fixture ships, so the only
// difference left is the rounding of the recorded answers: v_mps at 6 dp gives a 5e-7 half-ulp
// and fz at 1 dp gives 0.05 N, and both are hit exactly. if either of these ever fires it is a
// port divergence, because there is nothing else left in the budget for it to be.
const V_TOLERANCE_MPS = 5e-6;
const FZ_TOLERANCE_N = 0.5;

// the real budget is one 60 fps frame: the grip slider re-solves on every drag event, so a
// solve that misses 16 ms drops a frame on the user's machine. that is a claim about the
// user's machine, though, and GitHub's shared 2-core runners measure this solve at ~42 ms
// against ~10 ms on a dev laptop. asserting 16 ms there would gate every deploy on runner
// weather rather than on the code, so CI gets a budget scaled past the observed spread while
// still catching the thing worth catching: an order-of-magnitude regression. the 16 ms claim
// is verified locally and, ultimately, in the browser.
const BUDGET_MS = process.env.CI ? 120 : 16;

interface Fixture {
  meta: { load_transfer_iters: number; cap_iters: number };
  s_m: number[];
  z_m: number[];
  kappa_1pm: number[];
  cases: {
    mu: number;
    lap_time_s: number;
    v_mps: number[];
    phase: string[];
    fz_front_n: number[];
    fz_rear_n: number[];
  }[];
}

function checkFixture(name: string, fixture: Fixture) {
  describe(name, () => {
    const solver = new VelocitySolver(fixture.s_m, fixture.kappa_1pm, fixture.z_m);

    it("uses the same fixed-point iteration counts as the Python solver", () => {
      // both counts are part of the model, not tuning knobs: a mismatch is a silent physics
      // divergence that the 0.1 m/s tolerance below would mostly absorb
      expect(LOAD_TRANSFER_ITERS).toBe(fixture.meta.load_transfer_iters);
      expect(CAP_ITERS).toBe(fixture.meta.cap_iters);
    });

    for (const testCase of fixture.cases) {
      it(`matches the Python solver at mu=${testCase.mu}`, () => {
        const result = solver.solve({ ...BASE_VEHICLE, mu: testCase.mu });

        expect(Math.abs(result.lapTimeS - testCase.lap_time_s)).toBeLessThan(1e-6);

        let maxError = 0;
        for (let i = 0; i < testCase.v_mps.length; i++) {
          maxError = Math.max(maxError, Math.abs(result.vMps[i] - testCase.v_mps[i]));
        }
        expect(maxError).toBeLessThan(V_TOLERANCE_MPS);
      });

      it(`matches the Python axle loads at mu=${testCase.mu}`, () => {
        // v(s) alone would not catch a sign error in the load transfer that happens to
        // cancel inside the composed budget, which is exactly the bug this model can have.
        // a genuine sign error is ~3000 N at peak braking, four orders clear of this bound.
        const result = solver.solve({ ...BASE_VEHICLE, mu: testCase.mu });
        let maxFront = 0;
        let maxRear = 0;
        for (let i = 0; i < testCase.fz_front_n.length; i++) {
          maxFront = Math.max(maxFront, Math.abs(result.fzFrontN[i] - testCase.fz_front_n[i]));
          maxRear = Math.max(maxRear, Math.abs(result.fzRearN[i] - testCase.fz_rear_n[i]));
        }
        expect(maxFront).toBeLessThan(FZ_TOLERANCE_N);
        expect(maxRear).toBeLessThan(FZ_TOLERANCE_N);
      });
    }

    it("phases broadly agree with the Python labels", () => {
      const testCase = fixture.cases[0];
      const result = solver.solve({ ...BASE_VEHICLE, mu: testCase.mu });
      let agree = 0;
      for (let i = 0; i < testCase.phase.length; i++) {
        const python = testCase.phase[i];
        const ts = result.phase[i];
        const matches =
          (python === "accel" && ts === PHASE_ACCEL) ||
          (python === "brake" && ts === PHASE_BRAKE) ||
          (python === "coast" && ts !== PHASE_ACCEL && ts !== PHASE_BRAKE);
        if (matches) agree += 1;
      }
      // near-threshold points may flip label on sub-0.1 m/s differences; 99% agreement
      // proves the port without demanding bit-identical floating point
      expect(agree / testCase.phase.length).toBeGreaterThan(0.99);
    });

    it("solves fast enough for a live slider (well under a frame)", () => {
      const vehicle = { ...BASE_VEHICLE, mu: 1.0 };
      solver.solve(vehicle); // warm up
      const t0 = performance.now();
      const runs = 20;
      for (let i = 0; i < runs; i++) solver.solve(vehicle);
      const perSolveMs = (performance.now() - t0) / runs;
      // logged unconditionally so a gradual regression is visible in CI output well before it
      // is large enough to trip the assertion
      console.log(`${name} solve: ${perSolveMs.toFixed(2)} ms/solve (budget ${BUDGET_MS} ms)`);
      expect(perSolveMs).toBeLessThan(BUDGET_MS);
    });
  });
}

checkFixture("Spa", spaFixture as Fixture);
checkFixture("Monza", monzaFixture as Fixture);
