// cross-language validation: the TS solver must reproduce the Python solver
// (offline/velocity/solver.py) on both committed circuit fixtures -- Spa (hilly, long) and
// Monza (flat, chicane-heavy) -- at every fixture mu. The fixtures are generated by
// offline/build_viewer_assets.py from the same line.json geometry the viewer ships.

import { describe, expect, it } from "vitest";
import monzaFixture from "./testdata/velocity_fixture_monza.json";
import spaFixture from "./testdata/velocity_fixture_spa.json";
import type { GT3Vehicle } from "./vehicle";
import { PHASE_ACCEL, PHASE_BRAKE, VelocitySolver } from "./velocity";

// mirrors offline/velocity/vehicle.py's DEFAULT_GT3; the fixture cases only vary mu
const BASE_VEHICLE: Omit<GT3Vehicle, "mu"> = {
  mass_kg: 1300.0,
  downforce_area_m2: 2.8,
  drag_area_m2: 1.35,
  power_w: 410_000.0,
  air_density_kgpm3: 1.225,
  g_mps2: 9.81,
  v_floor_mps: 2.0,
};

interface Fixture {
  s_m: number[];
  kappa_1pm: number[];
  cases: { mu: number; lap_time_s: number; v_mps: number[]; phase: string[] }[];
}

function checkFixture(name: string, fixture: Fixture) {
  describe(name, () => {
    const solver = new VelocitySolver(fixture.s_m, fixture.kappa_1pm);

    for (const testCase of fixture.cases) {
      it(`matches the Python solver at mu=${testCase.mu}`, () => {
        const result = solver.solve({ ...BASE_VEHICLE, mu: testCase.mu });

        expect(Math.abs(result.lapTimeS - testCase.lap_time_s)).toBeLessThan(0.1);

        let maxError = 0;
        for (let i = 0; i < testCase.v_mps.length; i++) {
          maxError = Math.max(maxError, Math.abs(result.vMps[i] - testCase.v_mps[i]));
        }
        expect(maxError).toBeLessThan(0.1);
      });
    }

    it("phases broadly agree with the Python labels", () => {
      const testCase = fixture.cases[0];
      const result = solver.solve({ ...BASE_VEHICLE, mu: testCase.mu });
      let agree = 0;
      for (let i = 0; i < testCase.phase.length; i++) {
        const python = testCase.phase[i];
        const ts = result.phase[i];
        const matches =
          (python === "accel" && ts === PHASE_ACCEL) ||
          (python === "brake" && ts === PHASE_BRAKE) ||
          (python === "coast" && ts !== PHASE_ACCEL && ts !== PHASE_BRAKE);
        if (matches) agree += 1;
      }
      // near-threshold points may flip label on sub-0.1 m/s differences; 99% agreement
      // proves the port without demanding bit-identical floating point
      expect(agree / testCase.phase.length).toBeGreaterThan(0.99);
    });

    it("solves fast enough for a live slider (well under a frame)", () => {
      const vehicle = { ...BASE_VEHICLE, mu: 1.0 };
      solver.solve(vehicle); // warm up
      const t0 = performance.now();
      const runs = 20;
      for (let i = 0; i < runs; i++) solver.solve(vehicle);
      const perSolveMs = (performance.now() - t0) / runs;
      expect(perSolveMs).toBeLessThan(16);
    });
  });
}

checkFixture("Spa", spaFixture as Fixture);
checkFixture("Monza", monzaFixture as Fixture);
