// headless screenshots of the viewer, so a visual change can be reviewed without committing,
// pushing, and waiting for Pages.
//
//   npm run shots                  every frame in SHOTS
//   npm run shots -- spa           only frames whose name contains "spa"
//
// It drives the app entirely through the query string (src/ui/urlState.ts), so there is no test
// hook, no injected state and no privileged build: every frame it captures is a URL a person can
// open. That is the point of the URL state, not a side effect of it.
//
// Two things make this slower than it looks and both are unavoidable. Headless Chromium has no
// GPU, so WebGL runs on SwiftShader's software rasteriser; and the scene compiles its shaders on
// first draw, bakes a one-frame <Environment>, and streams the GLB through Suspense. The wait is
// therefore "ready flag, then a fixed number of animation frames", not a networkidle: networkidle
// fires while the terrain is still black.

import { spawn } from "node:child_process";
import { mkdir, rm } from "node:fs/promises";
import { createServer } from "node:net";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { chromium } from "playwright";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = resolve(ROOT, "shots");
const VIEWPORT = { width: 1600, height: 900 };
/** animation frames to let pass after the ready flag, before capturing. */
const SETTLE_FRAMES = 90;
/** how long to wait for the ready flag before giving up on a frame. */
const READY_TIMEOUT_MS = 60_000;

// The two frames the README prints are captured here, by the same harness, from the same URLs as
// every other frame: a shot carrying `doc` also writes a committed JPEG to that repo path.
//
// This exists because those two images had drifted off the product and nothing said so. They were
// added in dd2f7f8 on the other side of the split the 2026-08-27 merge reconciled, so they
// photograph a viewer that predates the interface rebuild, self-hosted Archivo and the corner
// re-measurement, and they are both the work-lamp rendition while the default is daylight. Hand
// dropped images cannot go stale loudly. These can: `npm run shots` rewrites them, so a rebuild
// that changes what the viewer looks like leaves the drift sitting in `git status`.
//
// Retina because the README is read on laptop displays and the originals were 2880x1800; JPEG
// because these are photographs of a shaded 3D scene, where PNG costs about four times the bytes
// for nothing a reader can see.
const DOC_SCALE = 2;
const DOC_QUALITY = 82;

// [name, query, pins?]. Names are filenames, so keep them filesystem-safe.
//
// `pins` opens the rail and the dock. Those are hover-to-peek panels whose pinned state lives in
// localStorage (src/ui/useExpandable.ts), not in the URL, so a headless run with no pointer would
// otherwise only ever photograph them shut. Seeding the same key the app reads is honest: it is
// the state a user gets by clicking the pin, not a special mode.
//
// `doc` is a repo-relative path the frame is additionally written to, as a retina JPEG. Only the
// README's frames carry it, and they are their own entries rather than a flag on a review frame:
// a doc frame carries two query parameters the review frames deliberately do not.
//
// A committed image regenerated by a routine command has to be reproducible or the property it was
// wired for is worthless: if every run rewrites ~700 kB of JPEG, real drift is indistinguishable
// from the churn. Both halves of that are needed and `play=0` alone is not enough, which is worth
// knowing before someone drops one of them:
//
//   play=0    freezes the lap clock. Otherwise the car and the telemetry readout sit wherever the
//             clock reached during the settle, and each run photographs a different moment.
//   motion=0  stops the scene animation. It defaults to the OS's prefers-reduced-motion, which in
//             a headless browser means motion *on*, so the terrain kept shimmering under a frozen
//             car and the bytes still moved.
//
// With both, two runs in separate browsers produce byte-identical files -- measured, not assumed --
// so a diff here means the viewer changed.
//
// `furniture=0` is the third, and it is a choice about the pictures rather than about determinism:
// the poles, gantries and boards stand between the camera and the road in every frame that has
// them, and the README is selling the line and the terrain. The braking boards are the one real
// loss, and the braking report is where those are actually read anyway.
//
// The rail and the dock are the instrument panel, and a screenshot with them shut is a picture of
// a 3D scene rather than of this tool, so one frame pins them open. Only one, and not the one that
// would show them best: **with both pinned, a `corner:` viewpoint draws no road at all**, and the
// fitted overview clips the top of the circuit. Both reproduce at deviceScaleFactor 1, so this is
// the product and not the capture. verify-p0.mjs pins both panels for the desktop, plan and chase
// frames but never for a corner, which is why it has never been photographed. Until that is fixed
// the chase frame carries the panels, because it is the one that survives them.
const DOC_FIXED = "enter=1&furniture=0&play=0&motion=0";
const DOC_PINS = { dock: true, side: true };
const SHOTS = [
  // near-vertical rather than the raised three-quarter: the whole lap reads as a shape, every
  // corner is named on the line, and there is no empty sky to fill a hero frame with.
  ["doc-overview", `circuit=spa&view=top&${DOC_FIXED}`, { doc: "docs/overview.jpg" }],
  // the grip cost drawn rather than quoted. mu 1.15 against the ghost's reference 1.20 puts them
  // 20 m apart at Eau Rouge -- close enough that one frame holds both cars, far enough to read as
  // a gap. At 0.95 it is 105 m and the ghost is off the side of the picture.
  [
    "doc-eau-rouge",
    `circuit=spa&view=corner:Eau%20Rouge&mu=1.15&ghost=1&at=corner:Eau%20Rouge&${DOC_FIXED}`,
    { doc: "docs/eau-rouge.jpg" },
  ],
  // the second rendition, and the only one of the three that carries the panels: see DOC_PINS.
  // Seeked to La Source rather than Eau Rouge's straight approach, so the car is turned in and
  // braking -- red phase trace under it -- instead of sitting on flat, empty tarmac.
  [
    "doc-lamp",
    `circuit=spa&view=chase&theme=dark&at=corner:La%20Source&${DOC_FIXED}`,
    { doc: "docs/lamp.jpg", ...DOC_PINS },
  ],
  ["spa-overview", "circuit=spa&view=overview&enter=1"],
  ["spa-eau-rouge", "circuit=spa&view=corner:Eau%20Rouge&enter=1"],
  ["spa-eau-rouge-bare", "circuit=spa&view=corner:Eau%20Rouge&enter=1&furniture=0"],
  ["spa-chase", "circuit=spa&view=chase&enter=1"],
  ["spa-plan", "circuit=spa&view=top&enter=1"],
  ["monza-overview", "circuit=monza&view=overview&enter=1"],
  ["monza-lesmo", "circuit=monza&view=corner:Lesmo%201&enter=1"],
  ["monza-rettifilo", "circuit=monza&view=corner:Variante%20del%20Rettifilo&enter=1"],
  ["monza-start", "circuit=monza&view=start&enter=1"],
  // the second rendition. It was `theme=light` here, which stopped photographing anything the
  // moment light became the default: this shot and `spa-overview` were the same frame.
  ["spa-overview-lamp", "circuit=spa&view=overview&enter=1&theme=dark"],
  ["spa-chase-lamp", "circuit=spa&view=chase&enter=1&theme=dark"],
  // the instruments, which only exist when the dock is open
  ["spa-telemetry", "circuit=spa&view=chase&enter=1", { dock: true, side: true }],
  ["spa-delta", "circuit=spa&view=chase&enter=1&mu=0.95&ghost=1", { dock: true }],
  ["spa-corners", "circuit=spa&view=overview&enter=1&mu=0.95&ghost=1", { dock: true, tab: "corners" }],
  // a corner viewpoint with both panels pinned, which is the combination nothing photographed. It
  // currently draws no road: the corner's name sits over blank paper. Kept as the frame that shows
  // the fix when it lands, and shows the bug until then.
  ["spa-corner-both-pinned", "circuit=spa&view=corner:Eau%20Rouge&enter=1", { dock: true, side: true }],
  // the ghost, several laps in. This is the frame that used to show the two cars on opposite
  // sides of the circuit: they ran on independent clocks wrapping at their own lap times, so the
  // quicker ghost gained a whole lap periodically and the gap grew without bound. One shared
  // clock bounds it to a single lap's grip cost, and this shot is the evidence.
  ["spa-ghost-laps-in", "circuit=spa&view=overview&enter=1&mu=0.95&ghost=1", { dock: true, side: true, extraFrames: 1800 }],
  // motion proof: the same frame with the shimmer on and off. `npm run shots -- motion` then
  // comparing the two "-a"/"-b" pairs is what turns "the animation is not working" into an
  // answer, instead of squinting at a still.
  ["motion-on-a", "circuit=spa&view=top&enter=1&motion=1&play=0"],
  ["motion-on-b", "circuit=spa&view=top&enter=1&motion=1&play=0", { extraFrames: 90 }],
  ["motion-off-a", "circuit=spa&view=top&enter=1&motion=0&play=0"],
  ["motion-off-b", "circuit=spa&view=top&enter=1&motion=0&play=0", { extraFrames: 90 }],
];

async function freePort() {
  return new Promise((res, rej) => {
    const srv = createServer();
    srv.on("error", rej);
    srv.listen(0, "127.0.0.1", () => {
      const { port } = srv.address();
      srv.close(() => res(port));
    });
  });
}

/** start `vite preview` and resolve once it is actually answering. */
async function startServer(port) {
  // `detached` puts npx and everything it spawns in one process group, so `stopServer` can signal
  // the group. Killing the returned handle alone is not enough and quietly does not work: the
  // handle is the *npx wrapper*, which spawns `sh -c vite preview`, which spawns the node process
  // actually holding the port. Killing npx therefore orphans that grandchild, which keeps the
  // inherited stderr pipe open -- and a pipe with a listener on it holds the event loop, so the
  // harness never exited either, on success as much as on failure. The symptom is a run that
  // prints every frame and then hangs forever, with a preview server still on its port.
  const child = spawn(
    "npx",
    ["vite", "preview", "--port", String(port), "--strictPort", "--host", "127.0.0.1"],
    { cwd: ROOT, stdio: ["ignore", "pipe", "pipe"], detached: true },
  );
  child.stderr.on("data", (b) => process.stderr.write(`[vite] ${b}`));

  const base = `http://127.0.0.1:${port}/`;
  const deadline = Date.now() + 30_000;
  for (;;) {
    if (child.exitCode !== null) throw new Error(`vite preview exited with ${child.exitCode}`);
    try {
      const r = await fetch(base);
      if (r.ok) break;
    } catch {
      /* not up yet */
    }
    if (Date.now() > deadline) throw new Error(`vite preview did not answer on ${base}`);
    await new Promise((r) => setTimeout(r, 250));
  }
  return { child, base };
}

/** stop the whole `vite preview` process group started by startServer. */
function stopServer(child) {
  try {
    process.kill(-child.pid, "SIGTERM");
  } catch {
    /* already gone, or never grouped: fall back to the handle itself */
    child.kill();
  }
}

async function capture(page, base, name, query, pins = {}) {
  // seed the panel pins before any script runs, since useExpandable reads them during its first
  // render. Same localStorage keys the pin button writes.
  await page.addInitScript((p) => {
    try {
      localStorage.setItem("track-side:pin:dock", p.dock ? "1" : "0");
      localStorage.setItem("track-side:pin:side", p.side ? "1" : "0");
    } catch {
      /* storage unavailable: the shot is just taken with the panels shut */
    }
  }, pins);

  await page.goto(`${base}?${query}`, { waitUntil: "domcontentloaded" });

  await page.waitForFunction(() => window.__trackSideReady === true, null, {
    timeout: READY_TIMEOUT_MS,
  });

  // the corner report lives behind a tab that has no URL state, because it is a view of the dock
  // rather than a view of the circuit. Clicking it is what a person would do.
  if (pins.tab === "corners") {
    await page.getByRole("button", { name: "corners" }).click();
  }

  // let the GLB, the environment bake and the shader compiles land. Counting real animation
  // frames rather than sleeping means this tracks how slow the software rasteriser actually is
  // on this machine instead of guessing.
  await page.evaluate(
    (frames) =>
      new Promise((done) => {
        let left = frames;
        const tick = () => (left-- > 0 ? requestAnimationFrame(tick) : done());
        requestAnimationFrame(tick);
      }),
    SETTLE_FRAMES + (pins.extraFrames ?? 0),
  );

  const file = resolve(OUT, `${name}.png`);
  await page.screenshot({ path: file });

  // a doc frame is the same frame, written a second time where the README reads it from. Written
  // from the same settled page rather than a second run, so the committed image and the reviewable
  // one cannot disagree about what the viewer did.
  if (pins.doc) {
    const docFile = resolve(ROOT, pins.doc);
    await mkdir(dirname(docFile), { recursive: true });
    await page.screenshot({ path: docFile, type: "jpeg", quality: DOC_QUALITY });
    return `${file}  +  ${pins.doc}`;
  }
  return file;
}

async function main() {
  const filter = process.argv.slice(2).filter((a) => !a.startsWith("-"));
  const wanted = filter.length
    ? SHOTS.filter(([name]) => filter.some((f) => name.includes(f)))
    : SHOTS;
  if (!wanted.length) {
    console.error(`no shots match ${filter.join(", ")}. Known: ${SHOTS.map((s) => s[0]).join(", ")}`);
    process.exitCode = 1;
    return;
  }

  await rm(OUT, { recursive: true, force: true });
  await mkdir(OUT, { recursive: true });

  const { child, base } = await startServer(await freePort());
  // `channel: "chromium"` is load-bearing, not a preference. Playwright's default headless is the
  // old headless shell, and it composites this canvas wrong: the presented frame drops the top
  // `insets.bottom` rows of the drawing buffer, so with the dock open the upper half of the circuit
  // is missing and the corner labels hang over blank sheet. The WebGL buffer itself is correct
  // there (readPixels on the same frame returns the road at those rows, and a headed browser
  // screenshots it intact), so it is a capture artifact, and every frame this harness produced
  // before this line was lying about the product. The new headless mode composites it correctly.
  // Needs `npx playwright install chromium`.
  //
  // `SHOTS_CHROMIUM` overrides that with a path, for sandboxes that ship a browser Playwright did
  // not download and cannot: the pinned revision is not the installed one, and `channel` resolves
  // by revision. It must point at the **full** chromium binary, not `headless_shell` — the shell
  // is the build with the compositing bug described above, so pointing this at one would quietly
  // reintroduce every problem `channel` was added to fix.
  //
  // Everything from here down runs inside the try, so that the `finally` below is reached however
  // this fails. It was not always: the browser was launched outside it, so a launch that threw --
  // a missing or mismatched chromium, the single most likely failure on a fresh machine -- left
  // `vite preview` running with nothing to stop it. The spawned child keeps the event loop alive,
  // so the script did not exit either. It reported the error and then hung, holding a port, and a
  // second attempt started a second one.
  let browser = null;
  try {
    const exe = process.env.SHOTS_CHROMIUM;
    browser = await chromium.launch(
      exe ? { executablePath: exe } : { channel: "chromium" },
    );

    // surface page errors: a shader that fails to compile renders a black frame and otherwise
    // says nothing at all, which is the single most likely way this script lies to you
    const watch = (p) => {
      p.on("pageerror", (e) => console.error(`  ! page error: ${e.message}`));
      p.on("console", (m) => {
        if (m.type() === "error") console.error(`  ! console: ${m.text()}`);
      });
      return p;
    };

    const page = watch(await browser.newPage({ viewport: VIEWPORT, deviceScaleFactor: 1 }));
    // doc frames get their own page at DOC_SCALE. Same CSS viewport, so the layout under review is
    // the same one; only the pixel density differs, which is what a retina laptop already does.
    // Created lazily, since most runs ask for no doc frame and the software rasteriser makes a
    // second page cost real time.
    let docPage = null;
    const pageFor = async (pins) => {
      if (!pins?.doc) return page;
      docPage ??= watch(
        await browser.newPage({ viewport: VIEWPORT, deviceScaleFactor: DOC_SCALE }),
      );
      return docPage;
    };

    for (const [name, query, pins] of wanted) {
      const t0 = Date.now();
      try {
        const file = await capture(await pageFor(pins), base, name, query, pins);
        console.log(`${name}  ${((Date.now() - t0) / 1000).toFixed(1)}s  ${file}`);
      } catch (err) {
        console.error(`${name}  FAILED: ${err.message}`);
        process.exitCode = 1;
      }
    }
  } finally {
    await browser?.close();
    stopServer(child);
  }
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
